name: 多点APP

on:
  schedule:
    - cron: '0 4,14,23,24 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 多点果园'
        run: python3 dd_garden.py
        env:
            DD_GARDEN_COOKIE: ${{ secrets.DD_GARDEN_COOKIE }}  #必须
            BARK: ${{ secrets.BARK }}     # bark服务
            SCKEY: ${{ secrets.SCKEY }}   # server酱服务
    
